# Site settings
author: Jonathan Wong
title: Becoming a Software Engineer
header-img: img/home-bg.png
email: jonathan.wong110@gmail.com
copyright_name: Jonathan Wong
description: > # this means to ignore newlines until "baseurl:"
  My Journey of Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jonathanwong110

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
